# Generated by Django 4.2.7 on 2026-01-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chats_chats_user_id_987f9c_idx',
            old_name='chats_session_user_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='chats_chats_user_id_c0e08d_idx',
            old_name='chats_session_uf_idx',
        ),
        migrations.RenameIndex(
            model_name='folder',
            new_name='chats_folde_user_id_1793f2_idx',
            old_name='chats_folder_user_idx',
        ),
    ]
