# Generated by Django 4.2.7 on 2026-01-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='artifact',
            new_name='jobs_artifa_job_id_e21ea2_idx',
            old_name='jobs_artifact_job_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='artifact',
            new_name='jobs_artifa_created_df1940_idx',
            old_name='jobs_artifact_created_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_status_277b31_idx',
            old_name='jobs_job_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_provide_a6f4b0_idx',
            old_name='jobs_job_provider_status_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_user_id_ec4047_idx',
            old_name='jobs_job_user_status_idx',
        ),
    ]
