# Generated by Django 4.2.7 on 2026-01-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='auth_user_members_5b7f96_idx',
            old_name='users_user_membersh_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('active', '활성'), ('past_due', '연체'), ('canceled', '취소됨'), ('trialing', '체험 중')], default='active', help_text='멤버십 상태', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID', max_length=255, null=True),
        ),
    ]
